// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * AutoGence Resources Sidebar Configuration
 * Starting with actuator control API documentation
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main Documentation Sidebar
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Quick Start Guides
  quickStartSidebar: [
    'quick-start/intro',
    'quick-start/harfy-setup',
    'quick-start/harfy-10min',
  ],
};

export default sidebars;
